# Generated by Django 4.1.7 on 2023-03-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=300)),
            ],
        ),
    ]
