# Generated by Django 4.1.7 on 2023-05-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elmail', '0002_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
