# Generated by Django 4.1.7 on 2023-05-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elmail', '0003_alter_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(default='sent', max_length=30),
        ),
    ]
