# Generated by Django 4.1.7 on 2023-05-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpuser',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smtpuser',
            name='surname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
