# Generated by Django 4.1.7 on 2023-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_smtpuser_name_smtpuser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpuser',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='smtpuser',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
